import { t } from "../i18n";
import type { McpRequirements } from "./types";

/**
 * Ready-made MCP servers. The user picks one and only fills what it truly needs — a
 * token, a folder, a connection string — or nothing at all; OAuth servers open the
 * provider's own sign-in page. The command line and URL stay out of sight (they're here,
 * the way each server's docs say to run it).
 */
export interface McpSecretField {
  /** Header name (http) or env var (stdio) the value goes into. */
  key: string;
  label: string;
  help?: string;
  /** Where to create the token. */
  url?: string;
  /** Can be left empty (a database without a password). */
  optional?: boolean;
}

export interface McpParam {
  label: string;
  placeholder: string;
  kind: "folder" | "text";
  help?: string;
}

export interface McpPreset {
  id: string;
  name: string;
  blurb: string;
  transport: "stdio" | "http";
  command?: string;
  /** `{param}` is replaced by the user's `param` value. */
  args?: string;
  url?: string;
  /** "oauth": sign in through the browser. "token": paste a key. "none": just connect. */
  auth: "oauth" | "token" | "none";
  secrets?: McpSecretField[];
  param?: McpParam;
  /** Runtime the command needs, so the UI can warn before it fails. */
  needs?: keyof McpRequirements;
  docs: string;
  category: "code" | "docs" | "design" | "work" | "data" | "web" | "money" | "other";
  /** Something the user should know before connecting (e.g. a CLI login). */
  note?: string;
}

export const MCP_PRESETS: McpPreset[] = [
  {
    id: "github",
    name: "GitHub",
    blurb: t("مستودعات، PRs، issues والـ Actions — من حساب GitHub تبعك."),
    transport: "http",
    url: "https://api.githubcopilot.com/mcp/",
    auth: "token",
    secrets: [
      {
        key: "Authorization",
        label: t("توكن GitHub"),
        help: t("Personal access token (classic أو fine-grained) بصلاحيات repo وissues وpull requests. الصق التوكن بس — رفيق بيضيف Bearer لحاله."),
        url: "https://github.com/settings/tokens",
      },
    ],
    docs: "https://github.com/github/github-mcp-server",
    category: "code",
  },
  {
    id: "filesystem",
    name: "Filesystem",
    blurb: t("قراءة وكتابة ملفات بمجلدات بتحددها إنت (خارج مجلد المحادثة)."),
    transport: "stdio",
    command: "npx",
    args: "-y @modelcontextprotocol/server-filesystem {param}",
    auth: "none",
    param: { label: t("المجلد اللي بيقدر يوصله"), placeholder: "C:\\Users\\you\\Projects", kind: "folder" },
    needs: "npx",
    docs: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    category: "data",
  },
  {
    id: "memory",
    name: "Knowledge graph",
    blurb: t("ذاكرة على شكل رسم بياني للكيانات والعلاقات، بتضل بين الجلسات."),
    transport: "stdio",
    command: "npx",
    args: "-y @modelcontextprotocol/server-memory",
    auth: "none",
    needs: "npx",
    docs: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    category: "other",
  },
  {
    id: "sequential-thinking",
    name: "Sequential thinking",
    blurb: t("بيخلّي النموذج يفكّر خطوة خطوة بمسائل معقّدة ويراجع نفسه."),
    transport: "stdio",
    command: "npx",
    args: "-y @modelcontextprotocol/server-sequential-thinking",
    auth: "none",
    needs: "npx",
    docs: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    category: "other",
  },
  {
    id: "playwright",
    name: "Playwright",
    blurb: t("متصفح كامل من Microsoft: تصفّح، ضغط، تعبئة نماذج، ولقطات شاشة."),
    transport: "stdio",
    command: "npx",
    args: "-y @playwright/mcp@latest",
    auth: "none",
    needs: "npx",
    docs: "https://github.com/microsoft/playwright-mcp",
    category: "web",
  },
  {
    id: "fetch",
    name: "Fetch",
    blurb: t("بيجيب صفحة ويب وبيحوّلها لنص نظيف للنموذج."),
    transport: "stdio",
    command: "uvx",
    args: "mcp-server-fetch",
    auth: "none",
    needs: "uvx",
    docs: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    category: "web",
  },
  {
    id: "context7",
    name: "Context7",
    blurb: t("توثيق محدّث لأي مكتبة برمجية، بدل ما النموذج يخمّن من ذاكرته."),
    transport: "stdio",
    command: "npx",
    args: "-y @upstash/context7-mcp",
    auth: "none",
    needs: "npx",
    docs: "https://github.com/upstash/context7",
    category: "docs",
  },
  {
    id: "notion",
    name: "Notion",
    blurb: t("صفحات وقواعد بيانات Notion — بحث، قراءة، وإنشاء."),
    transport: "http",
    url: "https://mcp.notion.com/mcp",
    auth: "oauth",
    docs: "https://developers.notion.com/docs/mcp",
    category: "work",
  },
  {
    id: "linear",
    name: "Linear",
    blurb: t("مهام ومشاريع Linear من داخل المحادثة."),
    transport: "http",
    url: "https://mcp.linear.app/mcp",
    auth: "oauth",
    docs: "https://linear.app/docs/mcp",
    category: "work",
  },
  {
    id: "atlassian",
    name: "Atlassian (Jira & Confluence)",
    blurb: t("Jira وConfluence عبر خادم Atlassian الرسمي."),
    transport: "http",
    url: "https://mcp.atlassian.com/v1/mcp",
    auth: "oauth",
    docs: "https://github.com/atlassian/atlassian-mcp-server",
    category: "work",
  },
  {
    id: "sentry",
    name: "Sentry",
    blurb: t("الأخطاء والـ issues من Sentry، مع تفاصيلها."),
    transport: "http",
    url: "https://mcp.sentry.dev/mcp",
    auth: "oauth",
    docs: "https://docs.sentry.io/product/sentry-mcp/",
    category: "code",
  },
  {
    id: "supabase",
    name: "Supabase",
    blurb: t("جداول، استعلامات SQL، وإدارة مشاريع Supabase."),
    transport: "stdio",
    command: "npx",
    args: "-y @supabase/mcp-server-supabase@latest",
    auth: "token",
    secrets: [{ key: "SUPABASE_ACCESS_TOKEN", label: t("Access token من Supabase"), url: "https://supabase.com/dashboard/account/tokens" }],
    needs: "npx",
    docs: "https://supabase.com/docs/guides/getting-started/mcp",
    category: "data",
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    blurb: t("استعلامات وتعديلات على قاعدة Postgres — كل تعديل بياخد إذنك."),
    transport: "stdio",
    // Crystal DBA's postgres-mcp: reads and writes. It breaks on MCP SDK 2.x, hence the pin.
    command: "uvx",
    args: "--with mcp<2 postgres-mcp --access-mode=unrestricted {param}",
    auth: "none",
    param: {
      label: t("رابط الاتصال"),
      placeholder: "postgresql://user@localhost:5432/db",
      kind: "text",
      help: t("بدون كلمة المرور — إلها خانتها لحالها. إذا لصقت رابط فيه كلمة مرور، رفيق بيشيلها منه وبيحفظها بالخانة."),
    },
    secrets: [
      {
        key: "PGPASSWORD",
        label: t("كلمة المرور"),
        help: t("بتنحفظ بخزنة ويندوز (Credential Manager)، مش مع إعدادات الخادم. اتركها فاضية إذا القاعدة ما بدها كلمة مرور."),
        optional: true,
      },
    ],
    needs: "uvx",
    docs: "https://github.com/crystaldba/postgres-mcp",
    category: "data",
  },
  {
    id: "sqlite",
    name: "SQLite",
    blurb: t("استعلام وتحليل ملفات SQLite محلية."),
    transport: "stdio",
    command: "uvx",
    args: "mcp-server-sqlite --db-path {param}",
    auth: "none",
    param: { label: t("ملف قاعدة البيانات"), placeholder: "C:\\data\\app.db", kind: "text" },
    needs: "uvx",
    docs: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite",
    category: "data",
  },
  {
    id: "stripe",
    name: "Stripe",
    blurb: t("عملاء، فواتير، ومدفوعات Stripe."),
    transport: "http",
    url: "https://mcp.stripe.com",
    auth: "oauth",
    docs: "https://docs.stripe.com/mcp",
    category: "work",
  },
  {
    id: "firebase",
    name: "Firebase",
    blurb: t("مشاريع Firebase: Firestore، Auth، والاستضافة."),
    transport: "stdio",
    command: "npx",
    args: "-y firebase-tools@latest experimental:mcp",
    auth: "none",
    needs: "npx",
    note: t("بيستخدم تسجيل دخولك بـ firebase-tools (شغّل «npx firebase login» مرة بالطرفية)."),
    docs: "https://firebase.google.com/docs/cli/mcp-server",
    category: "data",
  },
  {
    id: "brave",
    name: "Brave Search",
    blurb: t("بحث ويب ومحلي عبر Brave (بمفتاح API)."),
    transport: "stdio",
    command: "npx",
    args: "-y @brave/brave-search-mcp-server",
    auth: "token",
    secrets: [{ key: "BRAVE_API_KEY", label: t("مفتاح Brave Search API"), url: "https://api-dashboard.search.brave.com/" }],
    needs: "npx",
    docs: "https://github.com/brave/brave-search-mcp-server",
    category: "web",
  },
  {
    id: "slack",
    name: "Slack",
    blurb: t("قنوات ورسائل Slack (توكن بوت)."),
    transport: "stdio",
    command: "npx",
    args: "-y @modelcontextprotocol/server-slack",
    auth: "token",
    secrets: [
      { key: "SLACK_BOT_TOKEN", label: t("Bot token (xoxb-…)"), url: "https://api.slack.com/apps" },
      { key: "SLACK_TEAM_ID", label: t("Team ID (T…)"), help: t("من رابط مساحة العمل أو إعدادات التطبيق.") },
    ],
    needs: "npx",
    docs: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/slack",
    category: "work",
  },
  {
    id: "figma",
    name: "Figma",
    blurb: t("ملفات وتصاميم Figma عبر الخادم الرسمي."),
    transport: "http",
    url: "https://mcp.figma.com/mcp",
    auth: "oauth",
    docs: "https://help.figma.com/hc/en-us/articles/32132100833559",
    category: "design",
  },
  {
    id: "cloudflare-docs",
    name: "Cloudflare docs",
    blurb: t("توثيق Cloudflare كامل، بدون مفتاح."),
    transport: "http",
    url: "https://docs.mcp.cloudflare.com/mcp",
    auth: "none",
    docs: "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
    category: "docs",
  },
  {
    id: "docker",
    name: "Docker",
    blurb: t("حاويات وصور Docker على جهازك."),
    transport: "stdio",
    command: "docker",
    args: "mcp gateway run",
    auth: "none",
    needs: "docker",
    docs: "https://docs.docker.com/ai/mcp-catalog-and-toolkit/",
    category: "code",
  },
  {
    id: "gitlab",
    name: "GitLab",
    blurb: t("مشاريع، merge requests، issues والـ pipelines من GitLab."),
    transport: "http",
    url: "https://gitlab.com/api/v4/mcp",
    auth: "oauth",
    docs: "https://docs.gitlab.com/user/gitlab_duo/model_context_protocol/mcp_server/",
    category: "code",
  },
  {
    id: "vercel",
    name: "Vercel",
    blurb: t("مشاريعك ونشراتك على Vercel، مع السجلات."),
    transport: "http",
    url: "https://mcp.vercel.com",
    auth: "oauth",
    docs: "https://vercel.com/docs/mcp/vercel-mcp",
    category: "code",
  },
  {
    id: "netlify",
    name: "Netlify",
    blurb: t("مواقع Netlify: إنشاء، نشر، وإعدادات."),
    transport: "http",
    url: "https://netlify-mcp.netlify.app/mcp",
    auth: "oauth",
    docs: "https://docs.netlify.com/build/build-with-ai/netlify-mcp-server/",
    category: "code",
  },
  {
    id: "cloudflare-workers",
    name: "Cloudflare Workers",
    blurb: t("Workers وKV وR2 وD1 بحساب Cloudflare تبعك."),
    transport: "http",
    url: "https://bindings.mcp.cloudflare.com/mcp",
    auth: "oauth",
    docs: "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
    category: "code",
  },
  {
    id: "cloudflare-observability",
    name: "Cloudflare observability",
    blurb: t("سجلات وأخطاء Workers لتعرف شو صار."),
    transport: "http",
    url: "https://observability.mcp.cloudflare.com/mcp",
    auth: "oauth",
    docs: "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
    category: "code",
  },
  {
    id: "semgrep",
    name: "Semgrep",
    blurb: t("فحص أمان الكود ونتائج Semgrep."),
    transport: "http",
    url: "https://mcp.semgrep.ai/mcp",
    auth: "oauth",
    docs: "https://semgrep.dev/docs/mcp",
    category: "code",
  },
  {
    id: "posthog",
    name: "PostHog",
    blurb: t("تحليلات المنتج، الأحداث، والـ feature flags."),
    transport: "http",
    url: "https://mcp.posthog.com/mcp",
    auth: "oauth",
    docs: "https://posthog.com/docs/model-context-protocol",
    category: "data",
  },
  {
    id: "jam",
    name: "Jam",
    blurb: t("تقارير الأخطاء من Jam مع السجلات والشبكة."),
    transport: "http",
    url: "https://mcp.jam.dev/mcp",
    auth: "oauth",
    docs: "https://jam.dev/docs/debug-a-jam/mcp",
    category: "code",
  },
  {
    id: "neon",
    name: "Neon",
    blurb: t("قواعد Postgres على Neon: فروع، جداول، واستعلامات."),
    transport: "http",
    url: "https://mcp.neon.tech/mcp",
    auth: "oauth",
    docs: "https://neon.com/docs/ai/neon-mcp-server",
    category: "data",
  },
  {
    id: "prisma",
    name: "Prisma Postgres",
    blurb: t("قواعد Prisma Postgres ومخططاتها وترحيلاتها."),
    transport: "http",
    url: "https://mcp.prisma.io/mcp",
    auth: "oauth",
    docs: "https://www.prisma.io/docs/postgres/integrations/mcp-server",
    category: "data",
  },
  {
    id: "airtable",
    name: "Airtable",
    blurb: t("قواعد وجداول Airtable — قراءة وتعديل."),
    transport: "http",
    url: "https://mcp.airtable.com/mcp",
    auth: "oauth",
    docs: "https://support.airtable.com/docs/using-the-airtable-mcp-server",
    category: "data",
  },
  {
    id: "todoist",
    name: "Todoist",
    blurb: t("مهامك ومشاريعك على Todoist."),
    transport: "http",
    url: "https://ai.todoist.net/mcp",
    auth: "oauth",
    docs: "https://www.todoist.com/help/articles/use-todoist-with-ai-assistants",
    category: "work",
  },
  {
    id: "clickup",
    name: "ClickUp",
    blurb: t("مهام، مستندات، ومحادثات ClickUp."),
    transport: "http",
    url: "https://mcp.clickup.com/mcp",
    auth: "oauth",
    docs: "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
    category: "work",
  },
  {
    id: "monday",
    name: "monday.com",
    blurb: t("لوحات ومهام monday.com."),
    transport: "http",
    url: "https://mcp.monday.com/mcp",
    auth: "oauth",
    docs: "https://developer.monday.com/apps/docs/mondaycom-mcp-integration",
    category: "work",
  },
  {
    id: "intercom",
    name: "Intercom",
    blurb: t("محادثات العملاء وجهات الاتصال على Intercom."),
    transport: "http",
    url: "https://mcp.intercom.com/mcp",
    auth: "oauth",
    docs: "https://developers.intercom.com/docs/guides/mcp",
    category: "work",
  },
  {
    id: "close",
    name: "Close",
    blurb: t("عملاء وصفقات Close CRM."),
    transport: "http",
    url: "https://mcp.close.com/mcp",
    auth: "oauth",
    docs: "https://help.close.com/docs/mcp-server",
    category: "work",
  },
  {
    id: "granola",
    name: "Granola",
    blurb: t("ملاحظات اجتماعاتك من Granola."),
    transport: "http",
    url: "https://mcp.granola.ai/mcp",
    auth: "oauth",
    docs: "https://docs.granola.ai/help-center/sharing/integrations/mcp",
    category: "work",
  },
  {
    id: "zapier",
    name: "Zapier",
    blurb: t("آلاف التطبيقات عبر Zapier — الأدوات اللي بتختارها إنت بحسابك."),
    transport: "http",
    url: "https://mcp.zapier.com/api/mcp/mcp",
    auth: "oauth",
    docs: "https://zapier.com/mcp",
    category: "work",
  },
  {
    id: "canva",
    name: "Canva",
    blurb: t("تصاميم Canva: بحث، إنشاء، وتصدير."),
    transport: "http",
    url: "https://mcp.canva.com/mcp",
    auth: "oauth",
    docs: "https://www.canva.dev/docs/mcp/",
    category: "design",
  },
  {
    id: "miro",
    name: "Miro",
    blurb: t("لوحات Miro: قراءة وإضافة عناصر."),
    transport: "http",
    url: "https://mcp.miro.com/",
    auth: "oauth",
    docs: "https://developers.miro.com/docs/mcp-intro",
    category: "design",
  },
  {
    id: "webflow",
    name: "Webflow",
    blurb: t("مواقع Webflow: الصفحات والـ CMS."),
    transport: "http",
    url: "https://mcp.webflow.com/mcp",
    auth: "oauth",
    docs: "https://developers.webflow.com/mcp/reference/overview",
    category: "web",
  },
  {
    id: "wix",
    name: "Wix",
    blurb: t("مواقع Wix ومتاجرها."),
    transport: "http",
    url: "https://mcp.wix.com/mcp",
    auth: "oauth",
    docs: "https://dev.wix.com/docs/sdk/articles/use-the-wix-mcp/about-the-wix-mcp",
    category: "web",
  },
  {
    id: "paypal",
    name: "PayPal",
    blurb: t("فواتير، طلبات، ومعاملات PayPal."),
    transport: "http",
    url: "https://mcp.paypal.com/mcp",
    auth: "oauth",
    docs: "https://developer.paypal.com/tools/mcp-server/",
    category: "money",
  },
  {
    id: "square",
    name: "Square",
    blurb: t("مدفوعات، طلبات، وكتالوج Square."),
    transport: "http",
    url: "https://mcp.squareup.com/sse",
    auth: "oauth",
    docs: "https://developer.squareup.com/docs/mcp",
    category: "money",
  },
  {
    id: "microsoft-learn",
    name: "Microsoft Learn",
    blurb: t("توثيق Microsoft الرسمي (Azure، .NET، Windows…) بدون مفتاح."),
    transport: "http",
    url: "https://learn.microsoft.com/api/mcp",
    auth: "none",
    docs: "https://learn.microsoft.com/en-us/training/support/mcp",
    category: "docs",
  },
  {
    id: "deepwiki",
    name: "DeepWiki",
    blurb: t("اسأل عن أي مستودع عام على GitHub واقرا توثيقه."),
    transport: "http",
    url: "https://mcp.deepwiki.com/mcp",
    auth: "none",
    docs: "https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    category: "docs",
  },
  {
    id: "aws-knowledge",
    name: "AWS Knowledge",
    blurb: t("توثيق AWS ومقالاتها وإرشاداتها، بدون مفتاح."),
    transport: "http",
    url: "https://knowledge-mcp.global.api.aws",
    auth: "none",
    docs: "https://awslabs.github.io/mcp/servers/aws-knowledge-mcp-server",
    category: "docs",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    blurb: t("نماذج، datasets، وSpaces على Hugging Face."),
    transport: "http",
    url: "https://huggingface.co/mcp",
    auth: "none",
    docs: "https://huggingface.co/settings/mcp",
    category: "docs",
  },
  {
    id: "exa",
    name: "Exa",
    blurb: t("بحث ويب مخصص للنماذج، بدون مفتاح."),
    transport: "http",
    url: "https://mcp.exa.ai/mcp",
    auth: "none",
    docs: "https://docs.exa.ai/reference/exa-mcp",
    category: "web",
  },
  {
    id: "chrome-devtools",
    name: "Chrome DevTools",
    blurb: t("Chrome حقيقي من Google: أداء، شبكة، كونسول، ولقطات."),
    transport: "stdio",
    command: "npx",
    args: "-y chrome-devtools-mcp@latest",
    auth: "none",
    needs: "npx",
    docs: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
    category: "web",
  },
  {
    id: "git",
    name: "Git",
    blurb: t("تاريخ، فروق، وcommits لمستودع git على جهازك."),
    transport: "stdio",
    command: "uvx",
    args: "mcp-server-git --repository {param}",
    auth: "none",
    param: { label: t("مجلد المستودع"), placeholder: "C:\\Users\\you\\Projects\\app", kind: "folder" },
    needs: "uvx",
    docs: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
    category: "code",
  },
];

export function presetById(id: string | null | undefined): McpPreset | undefined {
  return id ? MCP_PRESETS.find((p) => p.id === id) : undefined;
}

export const MCP_CATEGORY_LABEL: Record<McpPreset["category"], string> = {
  code: t("برمجة"),
  docs: t("توثيق"),
  design: t("تصميم"),
  work: t("شغل وفرق"),
  data: t("بيانات"),
  web: t("ويب"),
  money: t("مدفوعات"),
  other: t("أخرى"),
};

export const REQUIREMENT_LABEL: Record<keyof McpRequirements, string> = {
  node: "Node.js",
  npx: "Node.js (npx)",
  uvx: "uv (uvx)",
  python: "Python",
  docker: "Docker",
};

export const REQUIREMENT_URL: Record<keyof McpRequirements, string> = {
  node: "https://nodejs.org/",
  npx: "https://nodejs.org/",
  uvx: "https://docs.astral.sh/uv/getting-started/installation/",
  python: "https://www.python.org/downloads/",
  docker: "https://www.docker.com/products/docker-desktop/",
};
